telegram:
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
  useCustomEmojiFilter: false
  replaceAtWithHash: false
  replaceExcessiveSpaces: false
  removeNewlineSpaces: false
  suppressFileTooBigMessages: false
  suppressThisIsPrivateBotMessage: false
  token: '{{env "TELEGRAM_BOT_TOKEN"}}'
discord:
  skipOldMessages: true
  useNickname: false
  replyLength: 100
  maxReplyLines: 2
  suppressThisIsPrivateBotMessage: false
  enableCustomStatus: false
  customStatusMessage: TediCross
  useEmbeds: auto
  token: '{{env "TELEGRAM_BOT_TOKEN"}}'
debug: false
messageTimeoutAmount: 24
messageTimeoutUnit: hours
persistentMessageMap: false
bridges:
  - name: '{{env "BRIDGE_NAME_1"}}'
    direction: d2t
    telegram:
      chatId: '{{env "TELEGRAM_CHAT_ID_1"}}'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '{{env "DISCORD_CHANNEL_ID_1"}}'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
      disableWebPreviewOnTelegram: false
      useEmbeds: auto
  - name: '{{env "BRIDGE_NAME_2"}}'
    direction: d2t
    telegram:
      chatId: '{{env "TELEGRAM_CHAT_ID_2"}}'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      crossDeleteOnDiscord: false
    discord:
      channelId: '{{env "DISCORD_CHANNEL_ID_2"}}'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      crossDeleteOnTelegram: false
      disableWebPreviewOnTelegram: false
      useEmbeds: auto
